# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pathMotionUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
     = QtCore.QString.fromUtf8
except AttributeError:
    def (s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pathmotion_Dialog(object):
    def setupUi(self, pathmotion_Dialog):
        pathmotion_Dialog.setObjectName(("pathmotion_Dialog"))
        pathmotion_Dialog.resize(337, 323)
        pathmotion_Dialog.setWindowTitle(("PathMotion"))
        self.mastercontroller_lineEdit = QtGui.QLineEdit(pathmotion_Dialog)
        self.mastercontroller_lineEdit.setGeometry(QtCore.QRect(120, 50, 141, 21))
        self.mastercontroller_lineEdit.setToolTip(("If none defined, one will be created automatically"))
        self.mastercontroller_lineEdit.setText((""))
        self.mastercontroller_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mastercontroller_lineEdit.setReadOnly(True)
        self.mastercontroller_lineEdit.setPlaceholderText(("Define a master controller"))
        self.mastercontroller_lineEdit.setObjectName(("mastercontroller_lineEdit"))
        self.mastercontroller_pushButton = QtGui.QPushButton(pathmotion_Dialog)
        self.mastercontroller_pushButton.setGeometry(QtCore.QRect(270, 50, 41, 21))
        self.mastercontroller_pushButton.setToolTip(("If none defined, one will be created automatically"))
        self.mastercontroller_pushButton.setText(("< Get"))
        self.mastercontroller_pushButton.setObjectName(("mastercontroller_pushButton"))
        self.mastercontroller_label = QtGui.QLabel(pathmotion_Dialog)
        self.mastercontroller_label.setGeometry(QtCore.QRect(20, 50, 91, 21))
        self.mastercontroller_label.setText(("Master Controller:"))
        self.mastercontroller_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mastercontroller_label.setObjectName(("mastercontroller_label"))
        self.objects_label = QtGui.QLabel(pathmotion_Dialog)
        self.objects_label.setGeometry(QtCore.QRect(20, 110, 91, 19))
        self.objects_label.setText(("Object(s):"))
        self.objects_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objects_label.setObjectName(("objects_label"))
        self.objects_lineEdit = QtGui.QLineEdit(pathmotion_Dialog)
        self.objects_lineEdit.setGeometry(QtCore.QRect(120, 110, 141, 19))
        self.objects_lineEdit.setToolTip(("If none, only locators will be placed along the curve"))
        self.objects_lineEdit.setText((""))
        self.objects_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.objects_lineEdit.setReadOnly(True)
        self.objects_lineEdit.setPlaceholderText(("Define object(s)"))
        self.objects_lineEdit.setObjectName(("objects_lineEdit"))
        self.objects_pushButton = QtGui.QPushButton(pathmotion_Dialog)
        self.objects_pushButton.setGeometry(QtCore.QRect(270, 110, 41, 19))
        self.objects_pushButton.setToolTip(("If none, only locators will be placed along the curve"))
        self.objects_pushButton.setText(("< Get"))
        self.objects_pushButton.setObjectName(("objects_pushButton"))
        self.pathcurve_label = QtGui.QLabel(pathmotion_Dialog)
        self.pathcurve_label.setGeometry(QtCore.QRect(20, 140, 91, 19))
        self.pathcurve_label.setText(("Path Curve(s):"))
        self.pathcurve_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathcurve_label.setObjectName(("pathcurve_label"))
        self.pathcurve_lineEdit = QtGui.QLineEdit(pathmotion_Dialog)
        self.pathcurve_lineEdit.setGeometry(QtCore.QRect(120, 140, 141, 19))
        self.pathcurve_lineEdit.setToolTip(("at least one curve is required"))
        self.pathcurve_lineEdit.setText((""))
        self.pathcurve_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pathcurve_lineEdit.setReadOnly(True)
        self.pathcurve_lineEdit.setPlaceholderText(("Define path curve(s)"))
        self.pathcurve_lineEdit.setObjectName(("pathcurve_lineEdit"))
        self.pathcurve_pushButton = QtGui.QPushButton(pathmotion_Dialog)
        self.pathcurve_pushButton.setGeometry(QtCore.QRect(270, 140, 41, 19))
        self.pathcurve_pushButton.setToolTip(("at least one curve is required"))
        self.pathcurve_pushButton.setText(("< Get"))
        self.pathcurve_pushButton.setObjectName(("pathcurve_pushButton"))
        self.count_spinBox = QtGui.QSpinBox(pathmotion_Dialog)
        self.count_spinBox.setGeometry(QtCore.QRect(120, 170, 51, 20))
        self.count_spinBox.setMinimum(1)
        self.count_spinBox.setMaximum(9999)
        self.count_spinBox.setProperty("value", 10)
        self.count_spinBox.setObjectName(("count_spinBox"))
        self.count_label = QtGui.QLabel(pathmotion_Dialog)
        self.count_label.setGeometry(QtCore.QRect(20, 170, 90, 19))
        self.count_label.setText(("Count:"))
        self.count_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.count_label.setObjectName(("count_label"))
        self.preinfinity_label = QtGui.QLabel(pathmotion_Dialog)
        self.preinfinity_label.setGeometry(QtCore.QRect(20, 200, 90, 19))
        self.preinfinity_label.setText(("Pre-Infinity:"))
        self.preinfinity_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.preinfinity_label.setObjectName(("preinfinity_label"))
        self.postinfinity_label = QtGui.QLabel(pathmotion_Dialog)
        self.postinfinity_label.setGeometry(QtCore.QRect(20, 230, 90, 19))
        self.postinfinity_label.setText(("Post-Infinity:"))
        self.postinfinity_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.postinfinity_label.setObjectName(("postinfinity_label"))
        self.preinfinity_comboBox = QtGui.QComboBox(pathmotion_Dialog)
        self.preinfinity_comboBox.setGeometry(QtCore.QRect(120, 200, 111, 20))
        self.preinfinity_comboBox.setObjectName(("preinfinity_comboBox"))
        self.preinfinity_comboBox.addItem((""))
        self.preinfinity_comboBox.setItemText(0, ("Cycle"))
        self.preinfinity_comboBox.addItem((""))
        self.preinfinity_comboBox.setItemText(1, ("Cycle with Offset"))
        self.preinfinity_comboBox.addItem((""))
        self.preinfinity_comboBox.setItemText(2, ("Oscillate"))
        self.preinfinity_comboBox.addItem((""))
        self.preinfinity_comboBox.setItemText(3, ("Linear"))
        self.preinfinity_comboBox.addItem((""))
        self.preinfinity_comboBox.setItemText(4, ("Constant"))
        self.postinfinity_comboBox = QtGui.QComboBox(pathmotion_Dialog)
        self.postinfinity_comboBox.setGeometry(QtCore.QRect(120, 230, 111, 20))
        self.postinfinity_comboBox.setObjectName(("postinfinity_comboBox"))
        self.postinfinity_comboBox.addItem((""))
        self.postinfinity_comboBox.setItemText(0, ("Cycle"))
        self.postinfinity_comboBox.addItem((""))
        self.postinfinity_comboBox.setItemText(1, ("Cycle with Offset"))
        self.postinfinity_comboBox.addItem((""))
        self.postinfinity_comboBox.setItemText(2, ("Oscillate"))
        self.postinfinity_comboBox.addItem((""))
        self.postinfinity_comboBox.setItemText(3, ("Linear"))
        self.postinfinity_comboBox.addItem((""))
        self.postinfinity_comboBox.setItemText(4, ("Constant"))
        self.nametemplate_label = QtGui.QLabel(pathmotion_Dialog)
        self.nametemplate_label.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.nametemplate_label.setText(("Name Template:"))
        self.nametemplate_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nametemplate_label.setObjectName(("nametemplate_label"))
        self.nametemplate_lineEdit = QtGui.QLineEdit(pathmotion_Dialog)
        self.nametemplate_lineEdit.setGeometry(QtCore.QRect(120, 20, 141, 21))
        self.nametemplate_lineEdit.setToolTip(("If none defined, default namings will be used"))
        self.nametemplate_lineEdit.setText((""))
        self.nametemplate_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.nametemplate_lineEdit.setReadOnly(False)
        self.nametemplate_lineEdit.setPlaceholderText(("Define a unique name"))
        self.nametemplate_lineEdit.setObjectName(("nametemplate_lineEdit"))
        self.controllerattr_label = QtGui.QLabel(pathmotion_Dialog)
        self.controllerattr_label.setGeometry(QtCore.QRect(20, 80, 91, 21))
        self.controllerattr_label.setText(("Controller Attr:"))
        self.controllerattr_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.controllerattr_label.setObjectName(("controllerattr_label"))
        self.controllerattr_lineEdit = QtGui.QLineEdit(pathmotion_Dialog)
        self.controllerattr_lineEdit.setGeometry(QtCore.QRect(120, 80, 141, 21))
        self.controllerattr_lineEdit.setToolTip(("If not specified a custom attribute named \"driver\" will be used"))
        self.controllerattr_lineEdit.setText((""))
        self.controllerattr_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.controllerattr_lineEdit.setReadOnly(True)
        self.controllerattr_lineEdit.setPlaceholderText(("Name for custom Attirubte"))
        self.controllerattr_lineEdit.setObjectName(("controllerattr_lineEdit"))
        self.create_pushButton = QtGui.QPushButton(pathmotion_Dialog)
        self.create_pushButton.setGeometry(QtCore.QRect(30, 270, 281, 31))
        self.create_pushButton.setText(("Create Path Objects"))
        self.create_pushButton.setObjectName(("create_pushButton"))

        QtCore.QMetaObject.connectSlotsByName(pathmotion_Dialog)


